# Generated by Django 4.2.29 on 2026-03-12 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Initial migration for the teams app.
    Creates: Skill, Team, TeamMembership, CodeRepository tables.
    Depends on organisation app (for Department FK) and AUTH_USER_MODEL.

    Author: Sarin Pradhan (Student 1)
    """

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Team mission and responsibilities')),
                ('status', models.CharField(
                    choices=[('active', 'Active'), ('restructured', 'Restructured'), ('disbanded', 'Disbanded')],
                    default='active', max_length=20
                )),
                ('slack_channel', models.CharField(blank=True, help_text='e.g. #team-name', max_length=100)),
                ('teams_channel', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='teams', to='organisation.department'
                )),
                ('manager', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='managed_teams', to=settings.AUTH_USER_MODEL
                )),
                ('skills', models.ManyToManyField(blank=True, to='teams.skill')),
                ('upstream_dependencies', models.ManyToManyField(
                    blank=True, related_name='downstream_dependents', to='teams.team'
                )),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CodeRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('platform', models.CharField(
                    choices=[('github', 'GitHub'), ('gitlab', 'GitLab'), ('bitbucket', 'Bitbucket'),
                             ('azure', 'Azure DevOps'), ('other', 'Other')],
                    default='github', max_length=20
                )),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='repositories', to='teams.team'
                )),
            ],
            options={
                'verbose_name_plural': 'Code Repositories',
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(
                    choices=[('engineer', 'Engineer'), ('senior_engineer', 'Senior Engineer'),
                             ('lead', 'Tech Lead'), ('manager', 'Manager'),
                             ('qa', 'QA Engineer'), ('devops', 'DevOps Engineer')],
                    default='engineer', max_length=30
                )),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='memberships', to='teams.team'
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='team_memberships', to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
    ]
